export const initialItems = [
  { id: 1, tipo: 'EPC', qtdePadrao: 3, descricao: 'Bay-pass de chave 13,8 e 34,5 kV' },
  { id: 2, tipo: 'EPC', qtdePadrao: 3, descricao: 'Jumper temporário 300A' },
  { id: 3, tipo: 'EPC', qtdePadrao: 1, descricao: 'Luva Anticorte para motoserrista' },
  { id: 4, tipo: 'EPC', qtdePadrao: 1, descricao: 'Detector de tensão BT' },
  { id: 5, tipo: 'EPC', qtdePadrao: 1, descricao: 'Detector de tensão MT' },
  { id: 6, tipo: 'EPC', qtdePadrao: 1, descricao: 'Detector de tensão AT' },
  { id: 7, tipo: 'EPC', qtdePadrao: 3, descricao: 'Bloqueador Sinalizador P/Chave Seccion (Bloqueador chave Faca)' },
  { id: 8, tipo: 'EPC', qtdePadrao: 1, descricao: 'Vara de manobra Telescópica 7 elementos (9,7mts)' },
  { id: 9, tipo: 'EPC', qtdePadrao: 1, descricao: 'Balde de lona' },
  { id: 10, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bastão "Pega Tudo" de no mínimo 2,58m' },
  { id: 11, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bastão podador' },
  { id: 12, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa para Bastao Pega Tudo' },
  { id: 13, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa para armazenar lençol isolante' },
  { id: 14, tipo: 'EPC', qtdePadrao: 2, descricao: 'Bolsa para Aterramento Primario' },
  { id: 15, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa para vara de manobra 4 elementos' },
  { id: 16, tipo: 'EPC', qtdePadrao: 1, descricao: 'Cabeçote universal para vara de manobra' },
  { id: 17, tipo: 'EPC', qtdePadrao: 1, descricao: 'Cabeçote universal para vara de manobra tipo DAQC' },
  { id: 18, tipo: 'EPC', qtdePadrao: 1, descricao: 'Calça e camisa Anticorte para motoserrista' },
  { id: 19, tipo: 'EPC', qtdePadrao: 6, descricao: 'Cone de sinalização -750mm (Laranja e branco)' },
  { id: 20, tipo: 'EPC', qtdePadrao: 2, descricao: 'Conjunto de aterramento primário 34,5 kV tipo torção' },
  { id: 21, tipo: 'EPC', qtdePadrao: 2, descricao: 'Conjunto de aterramento secundário para rede multiplexada' },
  { id: 22, tipo: 'EPC', qtdePadrao: 1, descricao: 'Corda de polipropileno/poliamida (11mm) com 30 metros' },
  { id: 23, tipo: 'EPC', qtdePadrao: 1, descricao: 'Dinamômetro para teste padrão 45 kgf' },
  { id: 24, tipo: 'EPC', qtdePadrao: 1, descricao: 'Escada extensível de Fibra de 2,53×3,66m (CP Rede)' },
  { id: 25, tipo: 'EPC', qtdePadrao: 1, descricao: 'Escada extensível 3,90×6,60 metros (BT) Fibra' },
  { id: 26, tipo: 'EPC', qtdePadrao: 1, descricao: 'Escada extensível 5,20×9,20 metros (AT) Fibra' },
  { id: 27, tipo: 'EPC', qtdePadrao: 1, descricao: 'Fita de Transposição' },
  { id: 28, tipo: 'EPC', qtdePadrao: 2, descricao: 'Fita refletiva com recolhedor de 30 metros' },
  { id: 29, tipo: 'EPC', qtdePadrao: 1, descricao: 'Gancho de ancoragem' },
  { id: 30, tipo: 'EPC', qtdePadrao: 9, descricao: 'Lençol isolante 1 kV' },
  { id: 31, tipo: 'EPC', qtdePadrao: 1, descricao: 'Load Buster - 13,8 kV' },
  { id: 32, tipo: 'EPC', qtdePadrao: 1, descricao: 'Load Buster - 34,5 kV' },
  { id: 33, tipo: 'EPC', qtdePadrao: 1, descricao: 'Macacão de proteção contra abelhas' },
  { id: 34, tipo: 'EPC', qtdePadrao: 2, descricao: 'Placa de interdição "não opere esta chave"' },
  { id: 35, tipo: 'EPC', qtdePadrao: 1, descricao: 'Vara de manobra com 4 elementos' },
  { id: 36, tipo: 'EPI', qtdePadrao: 1, descricao: 'Balde de lona para Linha de Vida' },
  { id: 37, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa de lona para luva isolante' },
  { id: 38, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa de lona para transporte de E. P. I.' },
  { id: 39, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa para armazenamento individual de ferramentas' },
  { id: 40, tipo: 'EPI', qtdePadrao: 3, descricao: 'Botina Impermeavel sem biqueira de aço com bidensidade' },
  { id: 41, tipo: 'EPI', qtdePadrao: 1, descricao: 'Capa contra chuva, pala dupla em PVC forrada, sem bolso com capuz.' },
  { id: 42, tipo: 'EPI', qtdePadrao: 1, descricao: 'Capa para capacete' },
  { id: 43, tipo: 'EPI', qtdePadrao: 1, descricao: 'Capacete Aba Frontal Classe B, com Identificação da Contratada' },
  { id: 44, tipo: 'EPI', qtdePadrao: 3, descricao: 'Capuz Balaclava anti-chama' },
  { id: 45, tipo: 'EPI', qtdePadrao: 1, descricao: 'Cinturão de segurança tipo para-quedista. PQD' },
  { id: 46, tipo: 'EPI', qtdePadrao: 1, descricao: 'Corda p/linha de vida poliamida (12mm) 30 m' },
  { id: 47, tipo: 'EPI', qtdePadrao: 2, descricao: 'Estojo para óculos de segurança' },
  { id: 48, tipo: 'EPI', qtdePadrao: 1, descricao: 'Fita Eureka com mosquetão e corda de amarração do topo da escada (Padrão Energisa)' },
  { id: 49, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de Borracha Isolante Classe 00' },
  { id: 50, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de Borracha Isolante, Classe III, 26,5 kV' },
  { id: 51, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de proteção de couro para luva de borracha Classe 00 ou 0' },
  { id: 52, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de proteção de couro para luva de borracha de 26.5 kV' },
  { id: 53, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de vaqueta para serviços gerais' },
  { id: 54, tipo: 'EPI', qtdePadrao: 1, descricao: 'Óculos de segurança com proteção lateral - lentes cinza' },
  { id: 55, tipo: 'EPI', qtdePadrao: 1, descricao: 'Óculos de segurança com proteção lateral - lentes transparentes' },
  { id: 56, tipo: 'EPI', qtdePadrao: 1, descricao: 'Perneira (par)' },
  { id: 57, tipo: 'EPI', qtdePadrao: 1, descricao: 'Protetor Facial com Bolsa p/ acondicionamento' },
  { id: 58, tipo: 'EPI', qtdePadrao: 1, descricao: 'Protetor solar fator 60' },
  { id: 59, tipo: 'EPI', qtdePadrao: 1, descricao: 'Talabarte de corda para cinturão de segurança PQD' },
  { id: 60, tipo: 'EPI', qtdePadrao: 1, descricao: 'Trava quedas para corda 11 mm' },
  { id: 61, tipo: 'EPI', qtdePadrao: 3, descricao: 'Uniforme Anti-Chama' },
  { id: 62, tipo: 'EPI', qtdePadrao: 2, descricao: 'Descensor corda antipático alumínio (Freio Eddy) mat 12,0mm' },
  { id: 63, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate MD6 / MD7 com Matrizes' },
  { id: 64, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate Hidráulico com Matrizes' },
  { id: 65, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Ponteira de Parafusadeira isolada - Bit Fenda' },
  { id: 66, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Ponteira de Parafusadeira isolada - Bit Philips' },
  { id: 67, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Marreta de 3 Kg' },
  { id: 68, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate bomba dágua 12" Isolado 1.000V' },
  { id: 69, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate Volt-amperímetro Classe 4' },
  { id: 70, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Arco de Serra com lâmina' },
  { id: 71, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Cadeado E40 e ou E-25 e ou E 20' },
  { id: 72, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Carretilha simples gancho longo de 454 kgf' },
  { id: 73, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Catraca de corrente 750 kg' },
  { id: 74, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave Allen de 4, 5, 6 E 8 mm Tipo T isolada p 1.000 V' },
  { id: 75, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave Borneira p/ CP Rede Isolado 1.000V' },
  { id: 76, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave carangueijo para CP-rede - isolada 1000V' },
  { id: 77, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave torta para CP-rede - isolada 1000 V' },
  { id: 78, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Escada de Centro' },
  { id: 79, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador para cabo de aço' },
  { id: 80, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador para condutor de 2/0AWG' },
  { id: 81, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador para condutor de 3/0AWG ate 336' },
  { id: 82, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Facão com bainha 18"' },
  { id: 83, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Farol auxiliar com extensão "Sealed Beam" (cilibim)' },
  { id: 84, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Furadeira/Parafusadeira Makita Dhp 456 Rhe 110 Volts Com 2 Baterias' },
  { id: 85, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Garrafa térmica de 5 litros' },
  { id: 86, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'GPS conforme especificação da Energisa' },
  { id: 87, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Guincho portátil 1250 kgf (catraca) tipo sirian' },
  { id: 88, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Lanterna portátil 15 a 19 led\'s Bateria alta duração' },
  { id: 89, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Lanterna portátil de Capacete' },
  { id: 90, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Máquina de bater conector "Ampact"' },
  { id: 91, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Marreta de 1 Kg' },
  { id: 92, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Moitão de aço, 3 gornes com capacidade de 3.000 Kg com corda (NA Base)' },
  { id: 93, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Motopoda' },
  { id: 94, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Motossera' },
  { id: 95, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Rádio de comunicação (Antena Grande)' },
  { id: 96, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Smartphone especificação da Energisa' },
  { id: 97, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Tesourão Pequeno Isolado' },
  { id: 98, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Trena 50m tipo fita' },
  { id: 99, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Alicate de corte diagonal - isolação 1000 V' },
  { id: 100, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Alicate de universal 8" - isolação 1000 V' },
  { id: 101, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Canivete sem ponta e com bainha' },
  { id: 102, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave ajustável de 12", cabo isolado 1000 V' },
  { id: 103, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave ajustável de 8", cabo isolado 1000 V' },
  { id: 104, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave de fenda - 1/4"×8" haste isolada 1000 V' },
  { id: 105, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave de fenda - 5/16"×8" haste isolada 1000 V' },
  { id: 106, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave 13mm isolada 1000 V Estrela' },
  { id: 107, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave Phillips 1/4 8mm Isolado 1.000 V' },
  { id: 108, tipo: 'EPC', qtdePadrao: 1, descricao: 'Agulhão de ancoragem com mosquetão' },
  { id: 109, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Conversor para carregar smartphone' },
  { id: 110, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Serrote Jack' },
  { id: 111, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Foice' },
  { id: 112, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Starlink Mini', somenteRural: true },
  { id: 113, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Adaptador veicular para Starlink Mini', somenteRural: true },
];

// Itens de OBRAS - Linha Viva (LV)
export const obrasLvItems = [
  { id: 2001, tipo: 'EPI', qtdePadrao: 3, descricao: 'Botina de segurança sem biqueira de aço e bidensidade' },
  { id: 2002, tipo: 'EPI', qtdePadrao: 1, descricao: 'Cinto de segurança paraquedista sem componentes metálicos' },
  { id: 2003, tipo: 'EPI', qtdePadrao: 3, descricao: 'Conjunto de uniformes anti-chama' },
  { id: 2004, tipo: 'EPI', qtdePadrao: 1, descricao: 'Perneira (par)' },
  { id: 2005, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de borracha isolante classe 2' },
  { id: 2006, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de borracha isolante classe 4' },
  { id: 2007, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luvas de vaqueta para serviços gerais' },
  { id: 2008, tipo: 'EPI', qtdePadrao: 1, descricao: 'Manga de borracha isolante bicolor classe 2' },
  { id: 2009, tipo: 'EPI', qtdePadrao: 1, descricao: 'Manga de borracha isolante bicolor classe 4' },
  { id: 2010, tipo: 'EPI', qtdePadrao: 1, descricao: 'Óculos de segurança lentes cinza' },
  { id: 2011, tipo: 'EPI', qtdePadrao: 1, descricao: 'Óculos de segurança lentes claras' },
  { id: 2012, tipo: 'EPI', qtdePadrao: 1, descricao: 'Talabarte para uso em cesto aéreo, tipo I' },
  { id: 2013, tipo: 'EPI', qtdePadrao: 1, descricao: 'Talabarte de corda tipo PQD' },
  { id: 2014, tipo: 'EPI', qtdePadrao: 1, descricao: 'Balaclava' },
  { id: 2015, tipo: 'EPC', qtdePadrao: 1, descricao: 'Banqueta isolada' },
  { id: 2016, tipo: 'EPC', qtdePadrao: 2, descricao: 'Bastão de tração espiral' },
  { id: 2017, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa para ferramentas' },
  { id: 2018, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa para mangas isolantes' },
  { id: 2019, tipo: 'EPC', qtdePadrao: 1, descricao: 'Suporte isolante classe IV' },
  { id: 2020, tipo: 'EPC', qtdePadrao: 1, descricao: 'Descascador de cabos' },
  { id: 2021, tipo: 'EPC', qtdePadrao: 1, descricao: 'Parafusadeira chave impacto com soquete' },
  { id: 2022, tipo: 'EPC', qtdePadrao: 3, descricao: 'Chave fusível temporária COD RC 600-1895' },
  { id: 2023, tipo: 'EPC', qtdePadrao: 3, descricao: 'Jumper temporário com cabo protegido 15kV para bucha de transformador COD FLV17448-1' },
  { id: 2024, tipo: 'EPC', qtdePadrao: 3, descricao: 'By-pass 1/0 isolado' },
  { id: 2025, tipo: 'EPC', qtdePadrao: 3, descricao: 'By-pass 2/0 isolado' },
  { id: 2026, tipo: 'EPC', qtdePadrao: 3, descricao: 'By-pass 4/0 até 336' },
  { id: 2027, tipo: 'EPC', qtdePadrao: 12, descricao: 'Cobertura circular 300mm Ø150mm fina' },
  { id: 2028, tipo: 'EPC', qtdePadrao: 12, descricao: 'Cobertura circular 600mm Ø150mm fina' },
  { id: 2029, tipo: 'EPC', qtdePadrao: 4, descricao: 'Cobertura circular 900mm Ø150mm fina' },
  { id: 2030, tipo: 'EPC', qtdePadrao: 6, descricao: 'Cobertura de condutor flexível classe II' },
  { id: 2031, tipo: 'EPC', qtdePadrao: 16, descricao: 'Cobertura de condutor flexível classe IV' },
  { id: 2032, tipo: 'EPC', qtdePadrao: 16, descricao: 'Cobertura de condutor rígida classe II' },
  { id: 2033, tipo: 'EPC', qtdePadrao: 16, descricao: 'Cobertura de condutor rígida classe IV' },
  { id: 2034, tipo: 'EPC', qtdePadrao: 2, descricao: 'Cobertura de cruzeta classe IV' },
  { id: 2035, tipo: 'EPC', qtdePadrao: 2, descricao: 'Cobertura para RDC espaçador losangular IV' },
  { id: 2036, tipo: 'EPC', qtdePadrao: 2, descricao: 'Cobertura para chave fusível flexível classe IV' },
  { id: 2037, tipo: 'EPC', qtdePadrao: 2, descricao: 'Cobertura para isolador de pino classe IV' },
  { id: 2038, tipo: 'EPC', qtdePadrao: 2, descricao: 'Cobertura para poste 1.200 mm' },
  { id: 2039, tipo: 'EPC', qtdePadrao: 2, descricao: 'Cobertura para poste 1.800 mm' },
  { id: 2040, tipo: 'EPC', qtdePadrao: 15, descricao: 'Cones de sinalização 750 mm, laranja e branco' },
  { id: 2041, tipo: 'EPC', qtdePadrao: 1, descricao: 'Conjunto de cruzeta auxiliar' },
  { id: 2042, tipo: 'EPC', qtdePadrao: 2, descricao: 'Escova de aço' },
  { id: 2043, tipo: 'EPC', qtdePadrao: 2, descricao: 'Fita de sinalização laranja' },
  { id: 2044, tipo: 'EPC', qtdePadrao: 1, descricao: 'Lona de proteção do sky (5 x 6 cm)' },
  { id: 2045, tipo: 'EPC', qtdePadrao: 1, descricao: 'Lona para material no solo (2 x 2 m)' },
  { id: 2046, tipo: 'EPC', qtdePadrao: 2, descricao: 'Lençol isolante 36 kV' },
  { id: 2047, tipo: 'EPC', qtdePadrao: 3, descricao: 'Lençol isolante com três entrelaçe 36 kV' },
  { id: 2048, tipo: 'EPC', qtdePadrao: 3, descricao: 'Lençol isolante bi-partido 36 kV' },
  { id: 2049, tipo: 'EPC', qtdePadrao: 6, descricao: 'Lençol ISO II NBR 2mm 300x900mm LJ para BT 1kV' },
  { id: 2050, tipo: 'EPC', qtdePadrao: 1, descricao: 'Plataforma isolante' },
  { id: 2051, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Alicate universal nº 8' },
  { id: 2052, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate bomba d\'água isolado 1 kV' },
  { id: 2053, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Balde de lona e couro para ferramentas' },
  { id: 2054, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa para luvas isolantes' },
  { id: 2055, tipo: 'EPI', qtdePadrao: 1, descricao: 'Capacete aba total classe B com identificação da contratada' },
  { id: 2056, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Carretilha para elevação de material/corda de poliuretano' },
  { id: 2057, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave de fenda' },
  { id: 2058, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Catraca com fita de nylon 1 TN' },
  { id: 2059, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Catraca serra 1250 kgf com fita de nylon' },
  { id: 2060, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave com catraca (completa) isolação 1 kV' },
  { id: 2061, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave combinada 1/2\" isolação 1 kV' },
  { id: 2062, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave combinada 3/4\" isolação 1 kV' },
  { id: 2063, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave combinada 11/16\" isolação 1 kV' },
  { id: 2064, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave combinada 5/8\" isolação 1 kV' },
  { id: 2065, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave combinada 7/8\" isolação 1 kV' },
  { id: 2066, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave combinada 9/16\" isolação 1 kV' },
  { id: 2067, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave de regulagem 12\" isolada 1 kV' },
  { id: 2068, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Chave de regulagem 8\" isolada 1 kV' },
  { id: 2069, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Conjunto de aterramento temporário para veículo (conectado ao caminhão)' },
  { id: 2070, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Calço estabilizador de borracha para uso na patola (1 por patola)' },
  { id: 2071, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Detector de ausência de tensão' },
  { id: 2072, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Detector de tensão' },
  { id: 2073, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador para condutor alumínio 3/0 até 336' },
  { id: 2074, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador para cabo 2AWG a 4/0AWG COD 51E07.D30-CE' },
  { id: 2075, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador para cabo 4AWG a 1/0AWG COD 51.E07.D20-CE' },
  { id: 2076, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Estropo de nylon com argola 500mm' },
  { id: 2077, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Estropo de nylon com argola 800mm' },
  { id: 2078, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Estropo de nylon com argola 1200mm' },
  { id: 2079, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Máquina impact' },
  { id: 2080, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Marreta 1 kg' },
  { id: 2081, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Marreta 2 kg' },
  { id: 2082, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Morsa pequena nº1' },
  { id: 2083, tipo: 'Ferr. Colet', qtdePadrao: 12, descricao: 'Pregador de cobertura' },
  { id: 2084, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Talha manual com tirante de nylon 1500 kg' },
  { id: 2085, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Terçado (facão)' },
  { id: 2086, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Tesourão com cabo isolado pequeno' },
  { id: 2087, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Termo higrômetro' },
  { id: 2088, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Testador de fase com bastão prolongador' },
  { id: 2089, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate com cremalheira para corte de cabo com alma de aço' },
  { id: 2090, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Moto poda hidráulica (Stanley)' },
  { id: 2091, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Mangueira Flex não condutiva laranja 2,40m 3/8\" rosca 1/2\" NPT com mola e engates rápidos' },
];

// Itens de OBRAS - Linha Morta (LM)
export const obrasLmItems = [
  // EPI
  { id: 3001, tipo: 'EPI', qtdePadrao: 1, descricao: 'Agulhão de ancoragem para poste duplo T' },
  { id: 3002, tipo: 'EPI', qtdePadrao: 1, descricao: 'Balde de lona' },
  { id: 3003, tipo: 'EPI', qtdePadrao: 1, descricao: 'Balde de lona para Linha de Vida' },
  { id: 3004, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa de lona para luva isolante' },
  { id: 3005, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa de lona para transporte de EPI' },
  { id: 3006, tipo: 'EPI', qtdePadrao: 1, descricao: 'Bolsa/Maleta para armazenamento individual de ferramentas' },
  { id: 3007, tipo: 'EPI', qtdePadrao: 3, descricao: 'Botina impermeável sem biqueira de aço com bidensidade' },
  { id: 3008, tipo: 'EPI', qtdePadrao: 1, descricao: 'Capa contra chuva, pala dupla em PVC forrada, com bolso com capuz' },
  { id: 3009, tipo: 'EPI', qtdePadrao: 1, descricao: 'Capacete Aba Frontal Classe B com identificação da contratada' },
  { id: 3010, tipo: 'EPI', qtdePadrao: 1, descricao: 'Cinturão de segurança tipo para–quedista PQD' },
  { id: 3011, tipo: 'EPI', qtdePadrao: 1, descricao: 'Corda p/linha de vida poliamida 12mm – 25m' },
  { id: 3012, tipo: 'EPI', qtdePadrao: 1, descricao: 'Corda de polipropileno/poliamida 12mm – 12m' },
  { id: 3013, tipo: 'EPI', qtdePadrao: 1, descricao: 'Corda de polipropileno/poliamida 10mm – topo de escada' },
  { id: 3014, tipo: 'EPI', qtdePadrao: 1, descricao: 'Estojo para óculos de segurança' },
  { id: 3015, tipo: 'EPI', qtdePadrao: 1, descricao: 'Fita de transposição' },
  { id: 3016, tipo: 'EPI', qtdePadrao: 1, descricao: 'Fita Eureka com corda de amarração para topo de escada' },
  { id: 3017, tipo: 'EPI', qtdePadrao: 1, descricao: 'Gancho de ancoragem' },
  { id: 3018, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de borracha isolante Classe 00' },
  { id: 3019, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de borracha isolante Classe III 26,5 kV' },
  { id: 3020, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva proteção de couro para luva Classe 00' },
  { id: 3021, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva proteção de couro para luva Classe III' },
  { id: 3022, tipo: 'EPI', qtdePadrao: 1, descricao: 'Luva de vaqueta para serviços gerais' },
  { id: 3023, tipo: 'EPI', qtdePadrao: 1, descricao: 'Mosquetão' },
  { id: 3024, tipo: 'EPI', qtdePadrao: 1, descricao: 'Óculos proteção lateral - lentes cinza' },
  { id: 3025, tipo: 'EPI', qtdePadrao: 1, descricao: 'Óculos proteção lateral - lentes transparentes' },
  { id: 3026, tipo: 'EPI', qtdePadrao: 1, descricao: 'Perneira (par)' },
  { id: 3027, tipo: 'EPI', qtdePadrao: 1, descricao: 'Protetor solar' },
  { id: 3028, tipo: 'EPI', qtdePadrao: 1, descricao: 'Talabarte duplo PQD' },
  { id: 3029, tipo: 'EPI', qtdePadrao: 1, descricao: 'Trava quedas padrão' },
  { id: 3030, tipo: 'EPI', qtdePadrao: 1, descricao: 'Uniforme anti–chama' },

  // EPC
  { id: 3031, tipo: 'EPC', qtdePadrao: 7, descricao: 'Bandeirola sinalização de escada' },
  { id: 3032, tipo: 'EPC', qtdePadrao: 2, descricao: 'Bastão \"pega tudo\"' },
  { id: 3033, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bastão podador' },
  { id: 3034, tipo: 'EPC', qtdePadrao: 2, descricao: 'Bay-pass 13,8 kV e 34,5 kV' },
  { id: 3035, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa bastão pega–tudo' },
  { id: 3036, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa acondicionamento de mantas isolantes' },
  { id: 3037, tipo: 'EPC', qtdePadrao: 2, descricao: 'Bolsa aterramento primário' },
  { id: 3038, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa aterramento secundário' },
  { id: 3039, tipo: 'EPC', qtdePadrao: 1, descricao: 'Bolsa vara de manobra 4 elementos' },
  { id: 3040, tipo: 'EPC', qtdePadrao: 1, descricao: 'Cabeçote universal para vara manobra tipo QAQC' },
  { id: 3041, tipo: 'EPC', qtdePadrao: 15, descricao: 'Cone sinalização 750mm (laranja/branco)' },
  { id: 3042, tipo: 'EPC', qtdePadrao: 4, descricao: 'Conjunto aterramento primário 34,5 kV' },
  { id: 3043, tipo: 'EPC', qtdePadrao: 4, descricao: 'Conjunto aterramento secundário rede multiplexada' },
  { id: 3044, tipo: 'EPC', qtdePadrao: 4, descricao: 'Conjunto aterramento secundário tipo bastão' },
  { id: 3045, tipo: 'EPC', qtdePadrao: 1, descricao: 'Detector de tensão' },
  { id: 3046, tipo: 'EPC', qtdePadrao: 1, descricao: 'Escada extensível fibra 2,53x3,66m (CP Rede)' },
  { id: 3047, tipo: 'EPC', qtdePadrao: 3, descricao: 'Escada extensível 3,90 x 6,60m (BT Fibra)' },
  { id: 3048, tipo: 'EPC', qtdePadrao: 7, descricao: 'Escada extensível 5,20 x 9,20m (AT Fibra)' },
  { id: 3049, tipo: 'EPC', qtdePadrao: 1, descricao: 'Fita de ancoragem escada' },
  { id: 3050, tipo: 'EPC', qtdePadrao: 1, descricao: 'Fita refletiva com recolhedor 50m' },
  { id: 3051, tipo: 'EPC', qtdePadrao: 1, descricao: 'Load Buster 13,8kV' },
  { id: 3052, tipo: 'EPC', qtdePadrao: 1, descricao: 'Load Buster 34,5kV' },
  { id: 3053, tipo: 'EPC', qtdePadrao: 9, descricao: 'Mantas isolantes 1.000 V' },
  { id: 3054, tipo: 'EPC', qtdePadrao: 5, descricao: 'Macacão proteção contra abelhas' },
  { id: 3055, tipo: 'EPC', qtdePadrao: 1, descricao: 'Placa: \"Não opere esta chave\"' },
  { id: 3056, tipo: 'EPC', qtdePadrao: 1, descricao: 'Suporte para escada' },
  { id: 3057, tipo: 'EPC', qtdePadrao: 1, descricao: 'Vara de manobra 4 elementos' },

  // Ferramentas (coletivo por padrão)
  { id: 3058, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alavanca de aço' },
  { id: 3059, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Alicate bomba d’água 12” isolado 1.000V' },
  { id: 3060, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Alicate corte diagonal isolado 1.000V' },
  { id: 3061, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Alicate universal 8” isolado 1.000V' },
  { id: 3062, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Alicate volt-amperímetro Classe III' },
  { id: 3063, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Arco de serra com lâmina' },
  { id: 3064, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Arco de serra tipo Jack com lâmina' },
  { id: 3065, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Binóculo 12x50' },
  { id: 3066, tipo: 'Ferr. Ind', qtdePadrao: 2, descricao: 'Cadeado E-25 e E-20' },
  { id: 3067, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Cadeado E-40' },
  { id: 3068, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Caixa divisória p/ conectores e elo fusíveis' },
  { id: 3069, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Caixa ferramentas tampa lateral' },
  { id: 3070, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Canivete sem ponta c/ bainha' },
  { id: 3071, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Carretilha simples gancho longo 454 kgf' },
  { id: 3072, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Catraca de corrente 750kg' },
  { id: 3073, tipo: 'Ferr. Colet', qtdePadrao: 3, descricao: 'Cavadeira tipo americana' },
  { id: 3074, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Cavadeira tipo Vanga' },
  { id: 3075, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Celular' },
  { id: 3076, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave 13mm isolada 1.000V + estrela' },
  { id: 3077, tipo: 'Ferr. Ind', qtdePadrao: 4, descricao: 'Chave ajustável 12” isolada 1.000V' },
  { id: 3078, tipo: 'Ferr. Ind', qtdePadrao: 4, descricao: 'Chave ajustável 8” isolada 1.000V' },
  { id: 3079, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave de fenda 1/4” x 8” isolada 1.000V' },
  { id: 3080, tipo: 'Ferr. Ind', qtdePadrao: 4, descricao: 'Chave de fenda 5/16” x 8” isolada 1.000V' },
  { id: 3081, tipo: 'Ferr. Ind', qtdePadrao: 4, descricao: 'Chave de fenda haste para 1.000V 8mm x 150mm' },
  { id: 3082, tipo: 'Ferr. Ind', qtdePadrao: 4, descricao: 'Chave hexagonal série longa cromo–vanádio (5/16, 4mm, 5mm, 6mm)' },
  { id: 3083, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Chave Phillips 1/4” 8mm isolada 1.000V' },
  { id: 3084, tipo: 'Ferr. Ind', qtdePadrao: 1, descricao: 'Colher de pedreiro' },
  { id: 3085, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Dinamômetro' },
  { id: 3086, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Enxadão com cabo' },
  { id: 3087, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Extrator p/ conector ampacthino' },
  { id: 3088, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Escoa de aço' },
  { id: 3089, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador p/ cabo de aço' },
  { id: 3090, tipo: 'Ferr. Colet', qtdePadrao: 4, descricao: 'Esticador condutor 1/0 AWG' },
  { id: 3091, tipo: 'Ferr. Colet', qtdePadrao: 2, descricao: 'Esticador condutor 2/0 AWG até 336' },
  { id: 3092, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Estropo de nylon 10T' },
  { id: 3093, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Facão com bainha 18”' },
  { id: 3094, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Farol auxiliar c/ extensão “Sealed Beam”' },
  { id: 3095, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Foice c/ cabo' },
  { id: 3096, tipo: 'Ferr. Colet', qtdePadrao: 1, descricao: 'Garra p/ poste duplo T' },
  { id: 3097, tipo: 'Ferr. Colet', qtdePadrao: 4, descricao: 'Garrafa térmica 5L' },
];
